/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "\u{1}_ZN5ImGui42NewFrameUpdateHoveredWindowAndCaptureFlagsEv"]
    pub fn NewFrameUpdateHoveredWindowAndCaptureFlags();
}
